"""Added GST columns to Invoice and InvoiceItem

Revision ID: 323bc44a064a
Revises: 
Create Date: 2026-02-27 15:53:39.690712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323bc44a064a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_gst_bill', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('total_cgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sgst', sa.Float(), nullable=True))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sgst_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_column('sgst_amount')
        batch_op.drop_column('cgst_amount')
        batch_op.drop_column('gst_rate')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('total_sgst')
        batch_op.drop_column('total_cgst')
        batch_op.drop_column('is_gst_bill')

    # ### end Alembic commands ###
