"""Added client gst details and hsn code

Revision ID: 4be20fb45017
Revises: 323bc44a064a
Create Date: 2026-02-27 16:18:35.874357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be20fb45017'
down_revision = '323bc44a064a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gst_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_column('hsn_code')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('gst_no')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
